version: "2"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=prod_db_legoons_3482397
      - POSTGRES_USER=waterkeysflow198237
      - POSTGRES_PASSWORD=30JHDfw]{7126salmon!
    ports:
      - 5432:5432
  web:
    image: dmm107/ece-458:web-prod
    # build: .
    restart: always
    command: ./entrypoint_prod.sh
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - "8000"
    environment:
      - POSTGRES_DB=prod_db_legoons_3482397
      - POSTGRES_USER=waterkeysflow198237
      - POSTGRES_PASSWORD=30JHDfw]{7126salmon!g
      - VIRTUAL_HOST=hypothetical-transportation-legoons.colab.duke.edu
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=hypothetical-transportation-legoons.colab.duke.edu
      - LETSENCRYPT_EMAIL=dmm107@duke.edu
    depends_on:
      - db
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx/prod
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/code/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  
volumes:
  static_volume:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
