version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    image: dmm107/ece-458:web-prod
    command: ./entrypoint_prod.sh
    # command: bash -c "python hypothetical_transportation/manage.py makemigrations && "\
    #           "python hypothetical_transportation/manage.py migrate && "\
    #           "python hypothetical_transportation/manage.py loaddata hypothetical_transportation/backend/fixtures/data.json &&"\
    #           "python hypothetical_transportation/manage.py initadmin && "\
    #           "python hypothetical_transportation/manage.py runserver_plus 0.0.0.0:8000 --cert-file /etc/letsencrypt/live/hypothetical-transportation.colab.duke.edu/fullchain.pem --key-file /etc/letsencrypt/live/hypothetical-transportation.colab.duke.edu/privkey.pem"
    volumes:
      - .:/local
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
