version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  web:
    build: .
    command: ./entrypoint_local.sh
    # command: bash -c "python hypothetical_transportation/manage.py makemigrations && "\
    #           "python hypothetical_transportation/manage.py migrate && "\
    #           "python hypothetical_transportation/manage.py loaddata hypothetical_transportation/backend/fixtures/data.json &&"\
    #           "python hypothetical_transportation/manage.py initadmin && "\
    #           "python hypothetical_transportation/manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/code/staticfiles
      # - .:/code/
    # ports:
      # - "8000:8000"
    expose:
      - "8000"
      
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - static_volume:/code/staticfiles

volumes:
  static_volume: