version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    image: dmm107/ece-458:web-dev
    command: ./entrypoint_dev.sh
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - "8000"
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - VIRTUAL_HOST=ht-dev.colab.duke.edu
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=ht-dev.colab.duke.edu
      - LETSENCRYPT_EMAIL=dmm107@duke.edu
    depends_on:
      - db
volumes:
  static_volume:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
