export const GET_STUDENTS = 'GET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT'

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const GET_SCHOOL = 'GET_SCHOOL';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const GET_USERS = "GET_USERS"
export const DELETE_USER = "DELETE_USER"
export const ADD_USER = "ADD_USER"
export const SEARCH_USER = "SEARCH_USER"
export const GET_USER = "GET_USER"

export const POPULATE_TABLE = "POPULATE_TABLE";
export const DELETE_ITEM = "DELETE_ITEM"

export const GET_ROUTES = "GET_ROUTES"
export const DELETE_ROUTE = "DELETE_ROUTE"
export const ADD_ROUTE = "ADD_ROUTE"
export const GET_ROUTE = "GET_ROUTE"

export const GET_STUDENTS_IN_ROUTE = "LOAD_STUDENTS_IN_ROUTE"
export const GET_STUDENTS_WITHOUT_ROUTE = "LOAD_STUDENTS_WITHOUT_ROUTE"