export const GET_STUDENTS = 'GET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT'

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const GET_SCHOOLS = 'GET_SCHOOLS';
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const GET_SCHOOL = 'GET_SCHOOL';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const GET_USERS = "GET_USERS"
export const DELETE_USER = "DELETE_USER"
export const ADD_USER = "ADD_USER"
export const SEARCH_USER = "SEARCH_USER"
export const GET_USER = "GET_USER"
export const RESET_POSTED_USER = "RESET_POSTED_USER"

export const POPULATE_TABLE = "POPULATE_TABLE";
export const DELETE_ITEM = "DELETE_ITEM"

export const GET_ROUTES = "GET_ROUTES"
export const DELETE_ROUTE = "DELETE_ROUTE"
export const ADD_ROUTE = "ADD_ROUTE"
export const UPDATE_ROUTE = "UPDATE_ROUTE"
export const GET_ROUTE = "GET_ROUTE"
export const RESET_VIEWED_ROUTE = "RESET_VIEWED_ROUTE"
export const RESET_POSTED = "RESET_POSTED"

export const GET_STOPS = "GET_STOPS"
export const GET_STOP = "GET_STOP"
export const ADD_STOP = "ADD_STOP"
export const DELETE_STOP = "DELETE_STOP"

export const GET_STUDENTS_IN_ROUTE = "LOAD_STUDENTS_IN_ROUTE"
export const GET_STUDENTS_WITHOUT_ROUTE = "LOAD_STUDENTS_WITHOUT_ROUTE"
export const GET_IN_RANGE_STOP = "GET_IN_RANGE_STOP"

export const VALIDATE_BULK_IMPORT = "VALIDATE_BULK_IMPORT"
export const VALIDATION_LOADING = "VALIDATION_LOADING"
export const BULK_IMPORT_SUBMIT = "BULK_IMPORT_SUBMIT"
export const BULK_IMPORT_SUBMIT_LOADING = "BULK_IMPORT_SUBMIT_LOADING"