# Generated by Django 3.2.11 on 2022-02-20 21:30

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations

class Migration(migrations.Migration):

    initial = True

    operations = [
        CITextExtension(),
    ]