from django.db import models

# for available fieldtypes, go here https://docs.djangoproject.com/en/4.0/ref/models/fields/#field-types
# uuids: https://docs.djangoproject.com/en/4.0/ref/models/fields/#uuidfield
# but uuids if you leave them out will also be autogenerated


class User(model.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=256) # stored password hash
    address = models.CharField(max_length=140, blank=True) # ev1 required only if there are students belonging to this user
    admin = models.BooleanField(default=False) 


class Route(models.Model):
    name = model.CharField(max_length=100)
    description = model.TextField()


class School(models.Model):
    address = models.CharField(max_length=140)
    name = model.CharField(max_length=100)


class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    active = models.BooleanField(default=True)
    student_id = models.
    usid = models.ForeignKey(
        'School', 
        on_delete=models.CASCADE,
    )
    urid = models.ForeignKey(
        'Route', 
        on_delete=models.CASCADE,
    )
    uuid = models.ForeignKey(
        'User', 
        on_delete=models.CASCADE,
    )