name: Docker Image CI

on:
  push:
    branches: [ environments ]
  pull_request:
    branches: [ environments ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the web Docker image
        run: docker build . --file Dockerfile --tag ece-458:web-dev
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: docker push dmm107/ece-458:web-dev
        # uses: docker/build-push-action@v2
        # with:
        #   context: .
        #   push: true
        #   tags: dmm107/ece-458:dev