name: Build & Deploy [DEV]

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the web Docker image
        run: docker build . --file Dockerfile --tag dmm107/ece-458:web-dev
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: docker push dmm107/ece-458:web-dev
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          username: ${{secrets.DEV_SSH_USERNAME}}
          password: ${{secrets.DEV_SSH_PASSWORD}}
          script: |
            cd ece-458
            sudo docker-compose -f docker-compose.dev.yml build
            sudo docker-compose -f docker-compose.dev.yml up -d
