name: Build & Deploy [DEV]

on:
  push:
    branches: [ dev ]

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Web Docker Image
        run: docker build . --file Dockerfile --tag dmm107/ece-458:web-dev
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push dmm107/ece-458:web-dev
      - name: Deploy Docker Image
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          username: ${{secrets.DEV_SSH_USERNAME}}
          password: ${{secrets.DEV_SSH_PASSWORD}}
          script: |
            cd ece-458
            sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker-compose -f docker-compose.dev.yml pull
            sudo docker-compose -f docker-compose.dev.yml down --volumes
            sudo docker-compose -f docker-compose.dev.yml up -d --build
