name: Build & Deploy [PROD]

on:
  push:
    branches: [ main, new-prod-host ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Web Docker Image
        run: docker build . --file Dockerfile --tag dmm107/ece-458:web-prod
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push dmm107/ece-458:web-prod
      - name: Deploy Docker Image
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.PROD_SSH_HOST}}
          username: ${{secrets.PROD_SSH_USERNAME}}
          password: ${{secrets.PROD_SSH_PASSWORD}}
          script: |
            cd ece-458
            export POSTGRES_DB=${{secrets.POSTGRES_DB}}
            export POSTGRES_USER=${{secrets.POSTGRES_USER}}
            export POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
            sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml down --volumes
            sudo docker-compose -f docker-compose.prod.yml up -d --build
