name: Build & Deploy [PROD]

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.PROD_SSH_HOST}}
          username: ${{secrets.PROD_SSH_USERNAME}}
          password: ${{secrets.PROD_SSH_PASSWORD}}
          script: |
            cd ece-458
            sudo docker-compose build
            sudo docker-compose up -d
