name: Build & Deploy [DEV]

on:
  push:
    branches: [ test ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          username: ${{secrets.DEV_SSH_USERNAME}}
          password: ${{secrets.DEV_SSH_PASSWORD}}
          script: |
            cd ece-458
            sudo docker-compose -f docker-compose.dev.yml build
            sudo docker-compose -f docker-compose.dev.yml up -d
